### ISSUE TITLE
Issue with connecting

### ISSUE THREAD

**Issue by norgan** [nitobuendia/oura-custom-component#4] opened 2021-02-01 09:38 UTC
Logger: root
Source: custom_components/oura/sensor.py:245
First occurred: 20:37:13 (1 occurrences)
Last logged: 20:37:13

Couldn't fetch data for Oura ring sensor.

Logger: root
Source: custom_components/oura/api.py:165
First occurred: 20:37:13 (1 occurrences)
Last logged: 20:37:13

Unable to retrieve access token from file data.

**Comment by norgan** [comment] 2021-02-02 03:31
Token is not being saved to file 

{"code": null}

**Comment by norgan** [comment] 2021-02-02 03:36
The json file that comes back opens in the browser. Firefox has given me more info:

X-Firefox-Spdy | h2
-- | --
content-encoding | deflate
content-length | 263
content-type | application/json
date | Tue, 02 Feb 2021 03:34:23 GMT
server | nginx
x-served-by | home.norgan.net

{"message": "Oura OAuth code None for sensor.sleep_quality stored in oura-token-cache. The sensor API will use this code to retrieve the access token, store it and start fetching data on the next update. No further action is required from your side. Any errors on retrieving the API token will be logged. If you ever want to restart this OAuth process, simply delete the file oura-token-cache within the /config/ directory."}

**Comment by norgan** [comment] 2021-02-02 03:36
https://home.norgan.net/oura/oauth/setup?error=unauthorized_client&error_description=authorization%20grant%20not%20allowed%20for%20this%20client%20application&state=sleep_quality

**Comment by norgan** [comment] 2021-02-02 03:53
Found the problem. Need to tick these:
 Allow server-side authentication (grant-type code)
 Allow client-side authentication (grant-type token)

**Comment by nitobuendia** [comment] 2021-02-02 11:13
Hi @norgan , thanks for reporting. Do I understand that this is fixed now?

One note: I am not sure why, but usually when you restart the system it usually will log "Couldn't fetch data for Oura ring sensor.". However, if you do not see any other errors, or it repeated again, it's not an issue.

In your case, you had another error, but it seems that you have found the root cause. I think that part is documented on the [Getting Started](https://cloud.ouraring.com/docs/), but I do admit that their documentation is rather short.

**Comment by nitobuendia** [comment] 2021-05-11 13:32
Marking as fixed.

**Closed as completed by nitobuendia** 2021-05-11 13:32 UTC
